org.gradle.jvmargs=-Xmx4G

mod_id=string_utilities
mod_version=1.1
mod_name=String Utilities Mod
mod_description=A mod that provides more NBT string operations.
mod_license=MIT
mod_author=Myitian
mod_source=https://github.com/Myitian/StringUtilities
maven_group=net.myitian.string_utilities_mod

version_id=1.20
minecraft_version=1.20.2
supported_minecraft_version_fabric=>=1.20 <=1.21.4
supported_minecraft_version_forge=[1.20,1.20.4]
supported_minecraft_version_neoforge=[1.20.2,1.20.4]
supported_minecraft_version_forge_like=[1.20.5,1.21.4]
parchment_mappings=1.20.2:2023.12.10

enabled_platforms=fabric,forge,neoforge
fabric_loader_version=0.17.3
forge_version=1.20.2-48.1.0
neoforge_version=20.2.93
fabric_api_version=0.91.6+1.20.2