org.gradle.jvmargs=-Xmx4G

mod_id=string_utilities
mod_version=1.1
mod_name=String Utilities Mod
mod_description=A mod that provides more NBT string operations.
mod_license=MIT
mod_author=Myitian
mod_source=https://github.com/Myitian/StringUtilities
maven_group=net.myitian.string_utilities_mod

version_id=1.21.5
minecraft_version=1.21.6
supported_minecraft_version_fabric=>=1.21.5 <=1.21.11
supported_minecraft_version_forge=[1.21.5,1.21.11]
supported_minecraft_version_neoforge=[1.21.5,1.21.11]
parchment_mappings=1.21.6:2025.06.29

enabled_platforms=fabric,forge,neoforge
fabric_loader_version=0.17.3
forge_version=1.21.6-56.0.9
neoforge_version=21.6.20-beta
fabric_api_version=0.128.2+1.21.6