pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net" }
        maven { url "https://maven.architectury.dev" }
        maven { url "https://maven.minecraftforge.net" }
        maven { url "https://maven.neoforged.net" }
        gradlePluginPortal()
    }
}

include "common"
include "fabric"
include "forge"
include "forge-1.20.6"
include "neoforge"
project(":common").projectDir.mkdirs()
project(":fabric").projectDir.mkdirs()
project(":forge").projectDir.mkdirs()
project(":forge-1.20.6").projectDir.mkdirs()
project(":neoforge").projectDir.mkdirs()